sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: e39TRSLUNfdSeE6I59XgCaI3PNwcCXSI+xfrbJBgfLbfV0/ABxTfq5N0rGHhJUp9Au2nXX+u1HfWO8ouTO3oq9ZVr8F+3Ek5dn09Tnd2vxYJ2lxyC6qtz731bEcw/SenT7zQ9+pR0AN+F2X6GbHXoCpEPc5xXgLPeYEdwvJiSRUdIQNsJJMTqvtVNADIYYykKR5sJp6J+CJyYZm32huhLxfbPCOIRJYpH6ABraRUl2Bk6K+4lsRFiSGnLPA1wcnF1N9o2I4A5CoWW7Kx7giv67MT/yq7GBthvtEUzZme7m7REVhjy/U86AA87Mn4qTBgp+mxajdkX64kplpAYD6LJYH8aeQheBQKOP7t7OVX32WLPTDUYH3qd5+MXsuWSvENmVXb7Yzj0MCqgI7bA95VcE18jgizt1jRd6FcX+YtPks21aGlUKt6ogQcok2kepOF3x4wf5G25I4W97kC4o9r9UyH9mh7PS2lJke4Nf+eWOClY4ZRpoTv+QmakkxHf+sZqJfBNVsRQvegwk41XoKQCKfdPo5qqjR/p8NDSd4bl++59giU0xL1m+fibEpazQdIZ16oLeGOUmZUYYQUNGyvQgeEZZcDoeo7QdisZGozT1I1sn6nQQzd0HB1+AJewlIqSZXwVx9gNaCyhg/jVAfMta4IPUj+amSjPgGhVwo2ibk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Notes-By-the-Way-in-a-Sailor-s-Life_4673
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy